In [2]:
import random
from PIL import Image, ImageDraw
from collections import Counter
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

import torch
import torchvision
from torchvision import transforms as T
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor


In [26]:
import csv
import xml.etree.ElementTree as ET
import glob


# parse the XML file
f = open('./trainfile.csv', 'w')
writer = csv.writer(f)

l = []

# write the header row to the CSV file
header = ['filename', 'width', 'height', 'depth', 'segmented', 'name', 'pose', 'truncated', 'difficult',  'xmin', 'ymin', 'xmax', 'ymax']
writer.writerow(header)
urls = glob.glob('C:/Users/HP/OneDrive/Desktop/folder/Bone_fracture/fracture/training_annotations/*.xml')
url = 'C:/Users/HP/OneDrive/Desktop/folder/Bone_fracture/fracture/training_annotations/'

for i in range(0, 237):
    path = url + str(i) + '.xml'
    tree = ET.parse(path)
    root = tree.getroot()
    # iterate over the objects in the XML file
    for obj in root.findall('size'):
        width = obj.find('width').text
        height = obj.find('height').text
        depth = obj.find('depth').text

    # iterate over the objects in the XML file
    for obj in root.findall('object'):
        name = obj.find('name').text
        pose = obj.find('pose').text
        truncated = obj.find('truncated').text
        difficult = obj.find('difficult').text


        bndbox = obj.find('bndbox')
        xmin = int(bndbox.find('xmin').text)
        ymin = int(bndbox.find('ymin').text)
        xmax = int(bndbox.find('xmax').text)
        ymax = int(bndbox.find('ymax').text)

        # write the data row to the CSV file
        row = [root.find('filename').text, width, height, depth, root.find('segmented').text, name, pose, truncated, difficult, xmin, ymin, xmax, ymax]
        writer.writerow(row)
    l.append(root.find('filename').text)
    print(root.find('filename').text, "is completed")


0.jpg is completed
1.jpg is completed
2.jpg is completed
3.jpg is completed
4.jpg is completed
5.jpg is completed
6.jpg is completed
7.jpg is completed
8.jpg is completed
9.jpg is completed
10.jpg is completed
11.jpg is completed
12.jpg is completed
13.jpg is completed
14.jpg is completed
15.jpg is completed
16.jpg is completed
17.jpg is completed
18.jpg is completed
19.jpg is completed
20.jpg is completed
21.jpg is completed
22.jpg is completed
23.jpg is completed
24.jpg is completed
25.jpg is completed
26.jpg is completed
27.jpg is completed
28.jpg is completed
29.jpg is completed
30.jpg is completed
31.jpg is completed
32.jpg is completed
33.jpg is completed
34.jpg is completed
35.jpg is completed
36.jpg is completed
37.jpg is completed
38.jpg is completed
39.jpg is completed
40.jpg is completed
41.jpg is completed
42.jpg is completed
43.jpg is completed
44.jpg is completed
45.jpg is completed
46.jpg is completed
47.jpg is completed
48.jpg is completed
49.jpg is completed
50.jpg is 

In [36]:
import csv
import xml.etree.ElementTree as ET
import glob


# parse the XML file
f = open('./valfile.csv', 'w')
writer = csv.writer(f)

l = []

# write the header row to the CSV file
header = ['filename', 'width', 'height', 'depth', 'segmented', 'name', 'pose', 'truncated', 'difficult',  'xmin', 'ymin', 'xmax', 'ymax']
writer.writerow(header)
urls = glob.glob('C:/Users/HP/OneDrive/Desktop/folder/Bone_fracture/fracture/training_annotations/*.xml')
url = 'C:/Users/HP/OneDrive/Desktop/folder/Bone_fracture/fracture/validation_annotations/'

for i in range(0, 40):
    path = url + str(i) + '.xml'
    tree = ET.parse(path)
    root = tree.getroot()
    # iterate over the objects in the XML file
    for obj in root.findall('size'):
        width = obj.find('width').text
        height = obj.find('height').text
        depth = obj.find('depth').text

    # iterate over the objects in the XML file
    for obj in root.findall('object'):
        name = obj.find('name').text
        pose = obj.find('pose').text
        truncated = obj.find('truncated').text
        difficult = obj.find('difficult').text


        bndbox = obj.find('bndbox')
        xmin = int(bndbox.find('xmin').text)
        ymin = int(bndbox.find('ymin').text)
        xmax = int(bndbox.find('xmax').text)
        ymax = int(bndbox.find('ymax').text)

        # write the data row to the CSV file
        row = [root.find('filename').text, width, height, depth, root.find('segmented').text, name, pose, truncated, difficult, xmin, ymin, xmax, ymax]
        writer.writerow(row)
    l.append(root.find('filename').text)
    print(root.find('filename').text, "is completed")


0.jpg is completed
1.jpg is completed
2.jpg is completed
3.jpg is completed
4.jpg is completed
5.jpg is completed
6.jpg is completed
7.jpg is completed
8.jpg is completed
9.jpg is completed
10.jpg is completed
11.jpg is completed
12.jpg is completed
13.jpg is completed
14.jpg is completed
15.jpg is completed
16.jpg is completed
17.jpg is completed
18.jpg is completed
19.jpg is completed
20.jpg is completed
21.jpg is completed
22.jpg is completed
23.jpg is completed
24.jpg is completed
25.jpg is completed
26.jpg is completed
27.jpg is completed
28.jpg is completed
29.jpg is completed
30.jpg is completed
31.jpg is completed
32.jpg is completed
33.jpg is completed
34.jpg is completed
35.jpg is completed
36.jpg is completed
37.jpg is completed
38.jpg is completed
39.jpg is completed


In [37]:
print(len(l))


40


In [28]:
print(l[236])

236.jpg


In [3]:
import pandas as pd
import cv2
import numpy as np

In [4]:
data = pd.read_csv('./trainfile.csv')
valdata = pd.read_csv('./valfile.csv')

In [5]:
url_img = 'C:/Users/HP/OneDrive/Desktop/folder/Bone_fracture/fracture/training/'
url_val_img = url = 'C:/Users/HP/OneDrive/Desktop/folder/Bone_fracture/fracture/validation/'

In [6]:
s = '5.jpg'
path = url_img + s
img = cv2.imread(path)
# img =  Image.open(path)
bboxs = data[data['filename']==s]
for index, row in bboxs.iterrows():
    xmin = row['xmin']
    xmax = row['xmax']
    ymin = row['ymin']
    ymax = row['ymax']
    label = row['name']
    cv2.rectangle(img,(xmin,ymin),(xmax, ymax),(255,0,0), 1)
#     font = cv2.FONT_HERSHEY_SIMPLEX
#     cv2.putText(img, label, (xmin+5,ymin+15), font, 0.5, (0,255,0), 1)
img = cv2.resize(img, (512, 512))
cv2.imshow('image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
unique_train_img = data.filename.unique()
unique_val_img = valdata.filename.unique()

In [8]:
train_inds = list(range(unique_train_img.shape[0]) )
val_inds = list(range(unique_val_img.shape[0]) )

In [9]:
print(len(unique_train_img))

237


In [10]:
print(data)

    filename  width  height  depth  segmented      name         pose  \
0      0.jpg    617    1024      1          0  fracture  Unspecified   
1      1.jpg    442     442      1          0  fracture  Unspecified   
2      2.jpg      0       0      3          0  fracture  Unspecified   
3      3.jpg    768     923      1          0  fracture  Unspecified   
4      4.jpg    442     442      1          0  fracture  Unspecified   
..       ...    ...     ...    ...        ...       ...          ...   
288  232.jpg    972     997      1          0  fracture  Unspecified   
289  233.jpg    837    1024      3          0  fracture  Unspecified   
290  234.jpg    525     812      1          0  fracture  Unspecified   
291  235.jpg    284     418      3          0  fracture  Unspecified   
292  236.jpg    279     667      3          0  fracture  Unspecified   

     truncated  difficult  xmin  ymin  xmax  ymax  
0            0          0   341   686   445   805  
1            0          0   263

In [11]:
image_name = unique_train_img[5]

b = data[data.filename == image_name].values[:, 9:].astype("float")

print(b)
# print(b.shape)

[[159. 342. 209. 402.]
 [111. 351. 168. 415.]]


In [12]:
# img = Image.open(url_img + image_name).convert("RGB")
# img.show()
labels = torch.ones((b.shape[0]), dtype = torch.int64)
print(labels)
t = {}
t['b'] = torch.tensor(b)
t['l'] = labels
print(t)

tensor([1, 1])
{'b': tensor([[159., 342., 209., 402.],
        [111., 351., 168., 415.]], dtype=torch.float64), 'l': tensor([1, 1])}


In [13]:
print( unique_train_img[0], train_inds[0])
image_name = unique_train_img[0]
boxes = data[data.filename == image_name].values[:, 9:].astype("float")
print(boxes)

0.jpg 0
[[341. 686. 445. 805.]]


In [14]:
class CustDat(torch.utils.data.Dataset):
    def __init__(self, data, unique_imgs, indices):
        self.data = data
        self.unique_imgs = unique_imgs
        self.indices = indices
    def __len__(self):
        return len(self.indices)
    def __getitem__(self, idx):
        image_name = self.unique_imgs[self.indices[idx]]
        boxes = self.data[self.data.filename == image_name].values[:, 9:].astype("float")
        img = Image.open(url_img + image_name).convert("RGB")
        labels = torch.ones((boxes.shape[0]), dtype = torch.int64)
        target = {}
        target['boxes'] = torch.tensor(boxes)
        target['label'] = labels
        return T.ToTensor()(img), target
    

In [15]:
print(len(train_inds), len(val_inds))
print(train_inds)
print(val_inds)

237 40
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 22

In [16]:
import warnings
  

warnings.filterwarnings('ignore')

In [17]:
unique_val_img

array(['0.jpg', '1.jpg', '2.jpg', '3.jpg', '4.jpg', '5.jpg', '6.jpg',
       '7.jpg', '8.jpg', '9.jpg', '10.jpg', '11.jpg', '12.jpg', '13.jpg',
       '14.jpg', '15.jpg', '16.jpg', '17.jpg', '18.jpg', '19.jpg',
       '20.jpg', '21.jpg', '22.jpg', '23.jpg', '24.jpg', '25.jpg',
       '26.jpg', '27.jpg', '28.jpg', '29.jpg', '30.jpg', '31.jpg',
       '32.jpg', '33.jpg', '34.jpg', '35.jpg', '36.jpg', '37.jpg',
       '38.jpg', '39.jpg'], dtype=object)

In [18]:
def custom_collate(data):
    return data

In [19]:
# print( unique_train_img[0], train_inds[0])
for i in range(237):
    print(i)
    image_name =  unique_train_img[i]
    boxes = data[data.filename == image_name].values[:, 9:].astype("float")
    print(boxes)
train_inds
# a = CustDat(data,  unique_train_img, train_inds)
# __getitem__()

0
[[341. 686. 445. 805.]]
1
[[263. 235. 300. 278.]]
2
[[194.  38. 217.  67.]]
3
[[369. 610. 408. 661.]]
4
[[272. 275. 309. 326.]]
5
[[159. 342. 209. 402.]
 [111. 351. 168. 415.]]
6
[[806. 436. 884. 533.]]
7
[[126. 307. 180. 366.]]
8
[[ 595. 1023.  657. 1104.]]
9
[[114. 617. 257. 777.]]
10
[[291. 225. 352. 309.]]
11
[[479. 578. 568. 685.]]
12
[[285. 328. 342. 401.]]
13
[[170. 159. 278. 261.]]
14
[[181. 412. 249. 573.]]
15
[[489. 597. 533. 634.]]
16
[[187. 410. 244. 570.]]
17
[[307. 357. 357. 421.]]
18
[[479. 585. 568. 691.]]
19
[[558. 513. 649. 639.]]
20
[[102. 268. 161. 332.]]
21
[[ 63. 125. 107. 171.]
 [ 31. 141.  67. 180.]]
22
[[269. 299. 301. 334.]]
23
[[104. 205. 236. 358.]]
24
[[564. 517. 652. 632.]]
25
[[268. 300. 300. 335.]]
26
[[1343. 1366. 1507. 1545.]]
27
[[ 605.  499.  873.  915.]
 [ 899.  455. 1099.  834.]
 [1220.  557. 1339.  957.]]
28
[[ 683.  552.  886. 1005.]
 [1002.  610. 1144. 1026.]
 [1257.  750. 1412. 1155.]]
29
[[50. 43. 82. 87.]]
30
[[ 12.  64.  51. 113.]]
31
[[28

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [26]:
train_dl = torch.utils.data.DataLoader(CustDat(data,  unique_train_img, train_inds),
                                      batch_size = 10,
                                      shuffle = True,
                                      collate_fn = custom_collate,
                                      pin_memory = True if torch.cuda.is_available() else False)

val_dl = torch.utils.data.DataLoader(CustDat(valdata,  unique_val_img, val_inds),
                                      batch_size = 5,
                                      shuffle = True,
                                      collate_fn = custom_collate,
                                      pin_memory = True if torch.cuda.is_available() else False)

In [27]:
# for i in train_dl:
#     print(i)
print(len(train_dl), train_dl)
for i in train_dl:
    print(i)

24 <torch.utils.data.dataloader.DataLoader object at 0x0000017E8C55AC50>
[(tensor([[[0.4392, 0.2157, 0.2235,  ..., 0.2706, 0.2627, 0.5922],
         [0.3098, 0.0784, 0.0863,  ..., 0.1412, 0.1412, 0.4863],
         [0.3333, 0.0980, 0.0980,  ..., 0.1333, 0.1412, 0.5020],
         ...,
         [0.6588, 0.5176, 0.5294,  ..., 0.0902, 0.0980, 0.4824],
         [0.6549, 0.5137, 0.5294,  ..., 0.0902, 0.0980, 0.4824],
         [0.6314, 0.5137, 0.5137,  ..., 0.0941, 0.0941, 0.4471]],

        [[0.4392, 0.2157, 0.2235,  ..., 0.2706, 0.2627, 0.5922],
         [0.3098, 0.0784, 0.0863,  ..., 0.1412, 0.1412, 0.4863],
         [0.3333, 0.0980, 0.0980,  ..., 0.1333, 0.1412, 0.5020],
         ...,
         [0.6588, 0.5176, 0.5294,  ..., 0.0902, 0.0980, 0.4824],
         [0.6549, 0.5137, 0.5294,  ..., 0.0902, 0.0980, 0.4824],
         [0.6314, 0.5137, 0.5137,  ..., 0.0941, 0.0941, 0.4471]],

        [[0.4392, 0.2157, 0.2235,  ..., 0.2706, 0.2627, 0.5922],
         [0.3098, 0.0784, 0.0863,  ..., 0.1412, 

[(tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]]), {'boxes': tensor([[557., 533., 627., 609.]], dtype=torch.float64), 'label': tensor([1])}), (tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0

[(tensor([[[0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         ...,
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         ...,
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 

[(tensor([[[0.0471, 0.0471, 0.0471,  ..., 0.1176, 0.1373, 0.1647],
         [0.0471, 0.0471, 0.0510,  ..., 0.1176, 0.1373, 0.1647],
         [0.0510, 0.0510, 0.0549,  ..., 0.1137, 0.1373, 0.1647],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0471, 0.0471, 0.0471,  ..., 0.1176, 0.1373, 0.1647],
         [0.0471, 0.0471, 0.0510,  ..., 0.1176, 0.1373, 0.1647],
         [0.0510, 0.0510, 0.0549,  ..., 0.1137, 0.1373, 0.1647],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0471, 0.0471, 0.0471,  ..., 0.1176, 0.1373, 0.1647],
         [0.0471, 0.0471, 0.0510,  ..., 0.1176, 0.1373, 0.1647],
         [0.0510, 0.0510, 0.0549,  ..., 0.1137, 0.1373, 

[(tensor([[[0.0588, 0.0588, 0.0588,  ..., 0.0667, 0.0667, 0.0667],
         [0.0588, 0.0588, 0.0588,  ..., 0.0667, 0.0667, 0.0667],
         [0.0588, 0.0588, 0.0588,  ..., 0.0667, 0.0667, 0.0667],
         ...,
         [0.0588, 0.0588, 0.0588,  ..., 0.0588, 0.0588, 0.0588],
         [0.0588, 0.0588, 0.0588,  ..., 0.0588, 0.0588, 0.0588],
         [0.0510, 0.0510, 0.0510,  ..., 0.0588, 0.0588, 0.0588]],

        [[0.0588, 0.0588, 0.0588,  ..., 0.0667, 0.0667, 0.0667],
         [0.0588, 0.0588, 0.0588,  ..., 0.0667, 0.0667, 0.0667],
         [0.0588, 0.0588, 0.0588,  ..., 0.0667, 0.0667, 0.0667],
         ...,
         [0.0588, 0.0588, 0.0588,  ..., 0.0588, 0.0588, 0.0588],
         [0.0588, 0.0588, 0.0588,  ..., 0.0588, 0.0588, 0.0588],
         [0.0510, 0.0510, 0.0510,  ..., 0.0588, 0.0588, 0.0588]],

        [[0.0588, 0.0588, 0.0588,  ..., 0.0667, 0.0667, 0.0667],
         [0.0588, 0.0588, 0.0588,  ..., 0.0667, 0.0667, 0.0667],
         [0.0588, 0.0588, 0.0588,  ..., 0.0667, 0.0667, 

[(tensor([[[0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         ...,
         [0.1804, 0.1922, 0.1922,  ..., 0.0039, 0.0039, 0.0039],
         [0.1882, 0.2000, 0.1922,  ..., 0.0039, 0.0039, 0.0039],
         [0.1922, 0.2000, 0.1843,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         ...,
         [0.1804, 0.1922, 0.1922,  ..., 0.0039, 0.0039, 0.0039],
         [0.1882, 0.2000, 0.1922,  ..., 0.0039, 0.0039, 0.0039],
         [0.1922, 0.2000, 0.1843,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 

[(tensor([[[0.0314, 0.0314, 0.0314,  ..., 0.0510, 0.0784, 0.0118],
         [0.0863, 0.0863, 0.0863,  ..., 0.1098, 0.1294, 0.0471],
         [0.1059, 0.1059, 0.1059,  ..., 0.1373, 0.1451, 0.0510],
         ...,
         [0.0941, 0.0941, 0.0941,  ..., 0.1020, 0.0941, 0.0471],
         [0.0941, 0.0941, 0.0941,  ..., 0.1020, 0.0941, 0.0471],
         [0.0941, 0.0941, 0.0941,  ..., 0.1020, 0.0941, 0.0471]],

        [[0.0314, 0.0314, 0.0314,  ..., 0.0510, 0.0784, 0.0118],
         [0.0863, 0.0863, 0.0863,  ..., 0.1098, 0.1294, 0.0471],
         [0.1059, 0.1059, 0.1059,  ..., 0.1373, 0.1451, 0.0510],
         ...,
         [0.0941, 0.0941, 0.0941,  ..., 0.1020, 0.0941, 0.0471],
         [0.0941, 0.0941, 0.0941,  ..., 0.1020, 0.0941, 0.0471],
         [0.0941, 0.0941, 0.0941,  ..., 0.1020, 0.0941, 0.0471]],

        [[0.0314, 0.0314, 0.0314,  ..., 0.0510, 0.0784, 0.0118],
         [0.0863, 0.0863, 0.0863,  ..., 0.1098, 0.1294, 0.0471],
         [0.1059, 0.1059, 0.1059,  ..., 0.1373, 0.1451, 

[(tensor([[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.7176, 0.7255, 0.7294],
         [0.0000, 0.0000, 0.0000,  ..., 0.7137, 0.7255, 0.7294],
         [0.0000, 0.0000, 0.0000,  ..., 0.7137, 0.7294, 0.7373]],

        [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.7176, 0.7255, 0.7294],
         [0.0000, 0.0000, 0.0000,  ..., 0.7137, 0.7255, 0.7294],
         [0.0000, 0.0000, 0.0000,  ..., 0.7137, 0.7294, 0.7373]],

        [[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 

[(tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]]), {'boxes': tensor([[766., 684., 870., 791.]], dtype=torch.float64), 'label': tensor([1])}), (tensor([[[0.8510, 0.8118, 0.8078,  ..., 0.0039, 0.0039, 0.0039],
         [0.8078, 0.7569, 0.7412,  ..., 0.0000, 0.0000

[(tensor([[[0.9961, 1.0000, 1.0000,  ..., 0.1098, 0.1137, 0.1216],
         [0.9961, 1.0000, 1.0000,  ..., 0.1098, 0.1137, 0.1176],
         [0.9961, 1.0000, 1.0000,  ..., 0.1098, 0.1098, 0.1098],
         ...,
         [0.1333, 0.1294, 0.1294,  ..., 0.8824, 0.9176, 0.9333],
         [0.1333, 0.1294, 0.1294,  ..., 0.8824, 0.9216, 0.9412],
         [0.1333, 0.1294, 0.1294,  ..., 0.8863, 0.9255, 0.9490]],

        [[0.9961, 1.0000, 1.0000,  ..., 0.1098, 0.1137, 0.1216],
         [0.9961, 1.0000, 1.0000,  ..., 0.1098, 0.1137, 0.1176],
         [0.9961, 1.0000, 1.0000,  ..., 0.1098, 0.1098, 0.1098],
         ...,
         [0.1333, 0.1294, 0.1294,  ..., 0.8824, 0.9176, 0.9333],
         [0.1333, 0.1294, 0.1294,  ..., 0.8824, 0.9216, 0.9412],
         [0.1333, 0.1294, 0.1294,  ..., 0.8863, 0.9255, 0.9490]],

        [[0.9961, 1.0000, 1.0000,  ..., 0.1098, 0.1137, 0.1216],
         [0.9961, 1.0000, 1.0000,  ..., 0.1098, 0.1137, 0.1176],
         [0.9961, 1.0000, 1.0000,  ..., 0.1098, 0.1098, 

[(tensor([[[0.0157, 0.1059, 0.1686,  ..., 0.5686, 0.5373, 0.5020],
         [0.3059, 0.1765, 0.0667,  ..., 0.5569, 0.5255, 0.4902],
         [0.1725, 0.1255, 0.0745,  ..., 0.5529, 0.5176, 0.4863],
         ...,
         [0.1098, 0.1059, 0.1059,  ..., 0.1176, 0.1216, 0.1333],
         [0.1176, 0.1098, 0.1059,  ..., 0.1176, 0.1216, 0.1294],
         [0.1255, 0.1176, 0.1098,  ..., 0.1176, 0.1176, 0.1255]],

        [[0.0157, 0.1059, 0.1686,  ..., 0.5608, 0.5294, 0.4941],
         [0.3059, 0.1765, 0.0667,  ..., 0.5490, 0.5176, 0.4824],
         [0.1725, 0.1255, 0.0745,  ..., 0.5451, 0.5098, 0.4784],
         ...,
         [0.1098, 0.1059, 0.1059,  ..., 0.1137, 0.1176, 0.1294],
         [0.1176, 0.1098, 0.1059,  ..., 0.1137, 0.1176, 0.1255],
         [0.1255, 0.1176, 0.1098,  ..., 0.1137, 0.1137, 0.1216]],

        [[0.0157, 0.1059, 0.1686,  ..., 0.5647, 0.5333, 0.4980],
         [0.3059, 0.1765, 0.0667,  ..., 0.5529, 0.5216, 0.4863],
         [0.1725, 0.1255, 0.0745,  ..., 0.5490, 0.5137, 

[(tensor([[[0.0000, 0.0000, 0.0000,  ..., 0.0588, 0.0667, 0.0549],
         [0.0000, 0.0000, 0.0000,  ..., 0.0706, 0.0745, 0.0588],
         [0.0000, 0.0000, 0.0000,  ..., 0.0784, 0.0824, 0.0706],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 1.0000, 0.9725, 0.5373],
         [0.0000, 0.0000, 0.0000,  ..., 0.9882, 0.9608, 0.5647],
         [0.0000, 0.0000, 0.0000,  ..., 0.5294, 0.5490, 0.2196]],

        [[0.0000, 0.0000, 0.0000,  ..., 0.0588, 0.0667, 0.0549],
         [0.0000, 0.0000, 0.0000,  ..., 0.0706, 0.0745, 0.0588],
         [0.0000, 0.0000, 0.0000,  ..., 0.0784, 0.0824, 0.0706],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 1.0000, 0.9725, 0.5373],
         [0.0000, 0.0000, 0.0000,  ..., 0.9882, 0.9608, 0.5647],
         [0.0000, 0.0000, 0.0000,  ..., 0.5294, 0.5490, 0.2196]],

        [[0.0000, 0.0000, 0.0000,  ..., 0.0588, 0.0667, 0.0549],
         [0.0000, 0.0000, 0.0000,  ..., 0.0706, 0.0745, 0.0588],
         [0.0000, 0.0000, 0.0000,  ..., 0.0784, 0.0824, 

[(tensor([[[0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         [0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         [0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         ...,
         [0.0588, 0.0588, 0.0588,  ..., 0.0353, 0.0353, 0.0353],
         [0.0588, 0.0588, 0.0588,  ..., 0.0353, 0.0353, 0.0353],
         [0.0588, 0.0588, 0.0588,  ..., 0.0353, 0.0353, 0.0353]],

        [[0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         [0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         [0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         ...,
         [0.0588, 0.0588, 0.0588,  ..., 0.0353, 0.0353, 0.0353],
         [0.0588, 0.0588, 0.0588,  ..., 0.0353, 0.0353, 0.0353],
         [0.0588, 0.0588, 0.0588,  ..., 0.0353, 0.0353, 0.0353]],

        [[0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         [0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         [0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 

[(tensor([[[0.0000, 0.0000, 0.0000,  ..., 0.1608, 0.1608, 0.1608],
         [0.0000, 0.0000, 0.0000,  ..., 0.1608, 0.1608, 0.1608],
         [0.0000, 0.0000, 0.0000,  ..., 0.1608, 0.1608, 0.1608],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0627, 0.0627, 0.0627],
         [0.0000, 0.0000, 0.0000,  ..., 0.0627, 0.0627, 0.0627],
         [0.0000, 0.0000, 0.0000,  ..., 0.0627, 0.0627, 0.0627]],

        [[0.0000, 0.0000, 0.0000,  ..., 0.1608, 0.1608, 0.1608],
         [0.0000, 0.0000, 0.0000,  ..., 0.1608, 0.1608, 0.1608],
         [0.0000, 0.0000, 0.0000,  ..., 0.1608, 0.1608, 0.1608],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0627, 0.0627, 0.0627],
         [0.0000, 0.0000, 0.0000,  ..., 0.0627, 0.0627, 0.0627],
         [0.0000, 0.0000, 0.0000,  ..., 0.0627, 0.0627, 0.0627]],

        [[0.0000, 0.0000, 0.0000,  ..., 0.1608, 0.1608, 0.1608],
         [0.0000, 0.0000, 0.0000,  ..., 0.1608, 0.1608, 0.1608],
         [0.0000, 0.0000, 0.0000,  ..., 0.1608, 0.1608, 

[(tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]]), {'boxes': tensor([[104., 205., 236., 358.]], dtype=torch.float64), 'label': tensor([1])}), (tensor([[[0.0118, 0.0157, 0.0157,  ..., 0.8784, 0.8745, 0.9451],
         [0.0118, 0.0157, 0.0157,  ..., 0.8706, 0.8706

[(tensor([[[0.0157, 0.0039, 0.0000,  ..., 0.0118, 0.0118, 0.0118],
         [0.0000, 0.0000, 0.0039,  ..., 0.0118, 0.0118, 0.0118],
         [0.0000, 0.0000, 0.0000,  ..., 0.0078, 0.0078, 0.0078],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0157, 0.0039, 0.0000,  ..., 0.0118, 0.0118, 0.0118],
         [0.0000, 0.0000, 0.0039,  ..., 0.0118, 0.0118, 0.0118],
         [0.0000, 0.0000, 0.0000,  ..., 0.0078, 0.0078, 0.0078],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0157, 0.0039, 0.0000,  ..., 0.0118, 0.0118, 0.0118],
         [0.0000, 0.0000, 0.0039,  ..., 0.0118, 0.0118, 0.0118],
         [0.0000, 0.0000, 0.0000,  ..., 0.0078, 0.0078, 

[(tensor([[[0.0431, 0.0784, 0.0431,  ..., 0.0471, 0.0941, 0.0275],
         [0.4157, 0.8039, 0.8706,  ..., 0.8314, 0.8353, 0.7098],
         [0.4471, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 0.8745],
         ...,
         [0.4549, 1.0000, 0.9961,  ..., 0.9882, 0.9882, 0.8627],
         [0.4549, 1.0000, 0.9961,  ..., 1.0000, 1.0000, 0.8510],
         [0.4549, 1.0000, 0.9961,  ..., 1.0000, 1.0000, 0.8510]],

        [[0.0431, 0.0784, 0.0431,  ..., 0.0471, 0.0941, 0.0275],
         [0.4157, 0.8039, 0.8706,  ..., 0.8314, 0.8353, 0.7098],
         [0.4471, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 0.8745],
         ...,
         [0.4549, 1.0000, 0.9961,  ..., 0.9882, 0.9882, 0.8627],
         [0.4549, 1.0000, 0.9961,  ..., 1.0000, 1.0000, 0.8510],
         [0.4549, 1.0000, 0.9961,  ..., 1.0000, 1.0000, 0.8510]],

        [[0.0431, 0.0784, 0.0431,  ..., 0.0471, 0.0941, 0.0275],
         [0.4157, 0.8039, 0.8706,  ..., 0.8314, 0.8353, 0.7098],
         [0.4471, 1.0000, 1.0000,  ..., 1.0000, 1.0000, 

[(tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]]), {'boxes': tensor([[251., 186., 326., 274.]], dtype=torch.float64), 'label': tensor([1])}), (tensor([[[0.2510, 0.2510, 0.2275,  ..., 0.2510, 0.3098, 0.3725],
         [0.1882, 0.1843, 0.1608,  ..., 0.2471, 0.3098

[(tensor([[[0.0706, 0.0706, 0.0706,  ..., 0.0980, 0.0980, 0.0980],
         [0.0667, 0.0667, 0.0667,  ..., 0.0941, 0.0941, 0.0941],
         [0.0627, 0.0627, 0.0627,  ..., 0.0902, 0.0902, 0.0902],
         ...,
         [0.3216, 0.2824, 0.2431,  ..., 0.0510, 0.0510, 0.0510],
         [0.3373, 0.2941, 0.2510,  ..., 0.0510, 0.0510, 0.0510],
         [0.3451, 0.2980, 0.2549,  ..., 0.0510, 0.0510, 0.0510]],

        [[0.0706, 0.0706, 0.0706,  ..., 0.0980, 0.0980, 0.0980],
         [0.0667, 0.0667, 0.0667,  ..., 0.0941, 0.0941, 0.0941],
         [0.0627, 0.0627, 0.0627,  ..., 0.0902, 0.0902, 0.0902],
         ...,
         [0.3216, 0.2824, 0.2431,  ..., 0.0510, 0.0510, 0.0510],
         [0.3373, 0.2941, 0.2510,  ..., 0.0510, 0.0510, 0.0510],
         [0.3451, 0.2980, 0.2549,  ..., 0.0510, 0.0510, 0.0510]],

        [[0.0706, 0.0706, 0.0706,  ..., 0.0980, 0.0980, 0.0980],
         [0.0667, 0.0667, 0.0667,  ..., 0.0941, 0.0941, 0.0941],
         [0.0627, 0.0627, 0.0627,  ..., 0.0902, 0.0902, 

[(tensor([[[0.0078, 0.0078, 0.0078,  ..., 0.0078, 0.0078, 0.0078],
         [0.0078, 0.0078, 0.0078,  ..., 0.0078, 0.0078, 0.0078],
         [0.0078, 0.0078, 0.0078,  ..., 0.0078, 0.0078, 0.0078],
         ...,
         [0.0196, 0.0196, 0.0196,  ..., 0.0078, 0.0078, 0.0078],
         [0.0196, 0.0196, 0.0196,  ..., 0.0078, 0.0078, 0.0078],
         [0.0196, 0.0196, 0.0196,  ..., 0.0078, 0.0078, 0.0078]],

        [[0.0078, 0.0078, 0.0078,  ..., 0.0078, 0.0078, 0.0078],
         [0.0078, 0.0078, 0.0078,  ..., 0.0078, 0.0078, 0.0078],
         [0.0078, 0.0078, 0.0078,  ..., 0.0078, 0.0078, 0.0078],
         ...,
         [0.0196, 0.0196, 0.0196,  ..., 0.0078, 0.0078, 0.0078],
         [0.0196, 0.0196, 0.0196,  ..., 0.0078, 0.0078, 0.0078],
         [0.0196, 0.0196, 0.0196,  ..., 0.0078, 0.0078, 0.0078]],

        [[0.0078, 0.0078, 0.0078,  ..., 0.0078, 0.0078, 0.0078],
         [0.0078, 0.0078, 0.0078,  ..., 0.0078, 0.0078, 0.0078],
         [0.0078, 0.0078, 0.0078,  ..., 0.0078, 0.0078, 

[(tensor([[[0.0039, 0.0000, 0.0000,  ..., 0.1176, 0.1176, 0.1176],
         [0.0118, 0.0039, 0.0078,  ..., 0.1216, 0.1216, 0.1216],
         [0.0118, 0.0039, 0.0118,  ..., 0.1294, 0.1294, 0.1294],
         ...,
         [0.0000, 0.0039, 0.0000,  ..., 0.0549, 0.0431, 0.0392],
         [0.0000, 0.0039, 0.0000,  ..., 0.0549, 0.0471, 0.0471],
         [0.0039, 0.0039, 0.0000,  ..., 0.0471, 0.0431, 0.0392]],

        [[0.0039, 0.0000, 0.0000,  ..., 0.1176, 0.1176, 0.1176],
         [0.0118, 0.0039, 0.0078,  ..., 0.1216, 0.1216, 0.1216],
         [0.0118, 0.0039, 0.0118,  ..., 0.1294, 0.1294, 0.1294],
         ...,
         [0.0000, 0.0039, 0.0000,  ..., 0.0549, 0.0431, 0.0392],
         [0.0000, 0.0039, 0.0000,  ..., 0.0549, 0.0471, 0.0471],
         [0.0039, 0.0039, 0.0000,  ..., 0.0471, 0.0431, 0.0392]],

        [[0.0039, 0.0000, 0.0000,  ..., 0.1176, 0.1176, 0.1176],
         [0.0118, 0.0039, 0.0078,  ..., 0.1216, 0.1216, 0.1216],
         [0.0118, 0.0039, 0.0118,  ..., 0.1294, 0.1294, 

[(tensor([[[0.0667, 0.0667, 0.0667,  ..., 0.0667, 0.0667, 0.0667],
         [0.0667, 0.0667, 0.0667,  ..., 0.0667, 0.0667, 0.0667],
         [0.0667, 0.0667, 0.0667,  ..., 0.0667, 0.0667, 0.0667],
         ...,
         [0.0667, 0.0667, 0.0667,  ..., 0.0667, 0.0667, 0.0667],
         [0.0667, 0.0667, 0.0667,  ..., 0.0667, 0.0667, 0.0667],
         [0.0667, 0.0667, 0.0667,  ..., 0.0667, 0.0667, 0.0667]],

        [[0.0627, 0.0627, 0.0627,  ..., 0.0627, 0.0627, 0.0627],
         [0.0627, 0.0627, 0.0627,  ..., 0.0627, 0.0627, 0.0627],
         [0.0627, 0.0627, 0.0627,  ..., 0.0627, 0.0627, 0.0627],
         ...,
         [0.0627, 0.0627, 0.0627,  ..., 0.0627, 0.0627, 0.0627],
         [0.0627, 0.0627, 0.0627,  ..., 0.0627, 0.0627, 0.0627],
         [0.0627, 0.0627, 0.0627,  ..., 0.0627, 0.0627, 0.0627]],

        [[0.0549, 0.0549, 0.0549,  ..., 0.0549, 0.0549, 0.0549],
         [0.0549, 0.0549, 0.0549,  ..., 0.0549, 0.0549, 0.0549],
         [0.0549, 0.0549, 0.0549,  ..., 0.0549, 0.0549, 

[(tensor([[[0.0078, 0.0078, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0078, 0.0078, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0078, 0.0078, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         ...,
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.0078, 0.0078, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0078, 0.0078, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0078, 0.0078, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         ...,
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.0078, 0.0078, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0078, 0.0078, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0078, 0.0078, 0.0039,  ..., 0.0039, 0.0039, 

[(tensor([[[1.0000, 0.0902, 0.0941,  ..., 0.0745, 0.0745, 0.0745],
         [1.0000, 0.0902, 0.0941,  ..., 0.0745, 0.0745, 0.0745],
         [1.0000, 0.0863, 0.0941,  ..., 0.0745, 0.0784, 0.0784],
         ...,
         [1.0000, 0.0510, 0.0627,  ..., 0.0588, 0.0588, 0.0588],
         [1.0000, 0.0549, 0.0627,  ..., 0.0588, 0.0588, 0.0588],
         [1.0000, 0.0549, 0.0627,  ..., 0.0588, 0.0588, 0.0588]],

        [[1.0000, 0.0902, 0.0941,  ..., 0.0745, 0.0745, 0.0745],
         [1.0000, 0.0902, 0.0941,  ..., 0.0745, 0.0745, 0.0745],
         [1.0000, 0.0863, 0.0941,  ..., 0.0745, 0.0784, 0.0784],
         ...,
         [1.0000, 0.0510, 0.0627,  ..., 0.0588, 0.0588, 0.0588],
         [1.0000, 0.0549, 0.0627,  ..., 0.0588, 0.0588, 0.0588],
         [1.0000, 0.0549, 0.0627,  ..., 0.0588, 0.0588, 0.0588]],

        [[1.0000, 0.0902, 0.0941,  ..., 0.0745, 0.0745, 0.0745],
         [1.0000, 0.0902, 0.0941,  ..., 0.0745, 0.0745, 0.0745],
         [1.0000, 0.0863, 0.0941,  ..., 0.0745, 0.0784, 

In [28]:
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained = True)

num_classes = 2

in_features = model.roi_heads.box_predictor.cls_score.in_features

model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)

In [29]:
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')

In [23]:
if(torch.cuda.is_available()):
    device = torch.device("cuda")
    print(device, torch.cuda.get_device_name(0))
else:
    device = torch.device("cpu")
    print(device)

cpu


In [30]:
device

device(type='cpu')

In [31]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.001, momentum=0.9, weight_decay=0.0005)
num_epochs = 5

In [ ]:
model.to(device)
for epochs in range(num_epochs):
    epoch_loss = 0
    print("epochs = ", epochs)
    cnt = 1
    for data in train_dl:
#         print("Running")
        imgs = []
        targets = []
        for d in data:
            imgs.append(d[0].to(device))
            targ = {}
            targ['boxes'] = d[1]["boxes"].to(device)
            targ['labels'] = d[1]["label"].to(device)
            targets.append(targ)
#         print(imgs)
        loss_dict = model(imgs, targets)
        print(loss_dict)
        loss = sum(v for v in loss_dict.values())
        epoch_loss += loss.cpu().detach().numpy()
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print("cnt = ", cnt, "run")
        cnt+=1
    print(epoch_loss)
        

epochs =  0
{'loss_classifier': tensor(0.6953, grad_fn=<NllLossBackward0>), 'loss_box_reg': tensor(0.0146, grad_fn=<DivBackward0>), 'loss_objectness': tensor(0.1347, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>), 'loss_rpn_box_reg': tensor(0.0100, dtype=torch.float64, grad_fn=<DivBackward0>)}
cnt =  1 run
{'loss_classifier': tensor(0.5088, grad_fn=<NllLossBackward0>), 'loss_box_reg': tensor(0.0201, grad_fn=<DivBackward0>), 'loss_objectness': tensor(0.1756, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>), 'loss_rpn_box_reg': tensor(0.0172, dtype=torch.float64, grad_fn=<DivBackward0>)}
cnt =  2 run
{'loss_classifier': tensor(0.2665, grad_fn=<NllLossBackward0>), 'loss_box_reg': tensor(0.0325, grad_fn=<DivBackward0>), 'loss_objectness': tensor(0.1236, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>), 'loss_rpn_box_reg': tensor(0.0047, dtype=torch.float64, grad_fn=<DivBackward0>)}
cnt =  3 run
{'loss_classifier': tensor(0.1440, grad_fn=<NllLossBackward0>), 'loss_box_reg': tensor(0.0386,

In [ ]:
for i in train_dl:
    print(i)

[(tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]]), {'boxes': tensor([[635., 642., 717., 742.]], dtype=torch.float64), 'label': tensor([1])}), (tensor([[[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000

[(tensor([[[0.0784, 0.0824, 0.0667,  ..., 1.0000, 1.0000, 1.0000],
         [0.0745, 0.0784, 0.0667,  ..., 1.0000, 1.0000, 1.0000],
         [0.0627, 0.0745, 0.0627,  ..., 1.0000, 1.0000, 1.0000],
         ...,
         [0.0627, 0.0627, 0.0627,  ..., 0.9255, 0.9255, 0.9294],
         [0.0627, 0.0627, 0.0627,  ..., 0.9176, 0.9176, 0.9216],
         [0.0627, 0.0627, 0.0627,  ..., 0.9098, 0.9059, 0.9137]],

        [[0.0784, 0.0824, 0.0667,  ..., 1.0000, 1.0000, 1.0000],
         [0.0745, 0.0784, 0.0667,  ..., 1.0000, 1.0000, 1.0000],
         [0.0627, 0.0745, 0.0627,  ..., 1.0000, 1.0000, 1.0000],
         ...,
         [0.0627, 0.0627, 0.0627,  ..., 0.9294, 0.9294, 0.9333],
         [0.0627, 0.0627, 0.0627,  ..., 0.9216, 0.9216, 0.9255],
         [0.0627, 0.0627, 0.0627,  ..., 0.9137, 0.9098, 0.9176]],

        [[0.0863, 0.0902, 0.0745,  ..., 1.0000, 1.0000, 1.0000],
         [0.0824, 0.0863, 0.0745,  ..., 1.0000, 1.0000, 1.0000],
         [0.0706, 0.0824, 0.0706,  ..., 1.0000, 1.0000, 

[(tensor([[[0.0196, 0.0000, 0.0157,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0118, 0.0431,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0235,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.0039, 0.0039, 0.0039,  ..., 0.0000, 0.0000, 0.0000],
         [0.0039, 0.0039, 0.0039,  ..., 0.0000, 0.0000, 0.0000],
         [0.0039, 0.0039, 0.0039,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0196, 0.0000, 0.0157,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0118, 0.0431,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0235,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.0039, 0.0039, 0.0039,  ..., 0.0000, 0.0000, 0.0000],
         [0.0039, 0.0039, 0.0039,  ..., 0.0000, 0.0000, 0.0000],
         [0.0039, 0.0039, 0.0039,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0196, 0.0000, 0.0157,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0118, 0.0431,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0235,  ..., 0.0000, 0.0000, 

[(tensor([[[0.0157, 0.0039, 0.0000,  ..., 0.0118, 0.0118, 0.0118],
         [0.0000, 0.0000, 0.0039,  ..., 0.0118, 0.0118, 0.0118],
         [0.0000, 0.0000, 0.0000,  ..., 0.0078, 0.0078, 0.0078],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0157, 0.0039, 0.0000,  ..., 0.0118, 0.0118, 0.0118],
         [0.0000, 0.0000, 0.0039,  ..., 0.0118, 0.0118, 0.0118],
         [0.0000, 0.0000, 0.0000,  ..., 0.0078, 0.0078, 0.0078],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.0157, 0.0039, 0.0000,  ..., 0.0118, 0.0118, 0.0118],
         [0.0000, 0.0000, 0.0039,  ..., 0.0118, 0.0118, 0.0118],
         [0.0000, 0.0000, 0.0000,  ..., 0.0078, 0.0078, 

[(tensor([[[0.0078, 0.0157, 0.0078,  ..., 0.0078, 0.0078, 0.0078],
         [0.0078, 0.0157, 0.0078,  ..., 0.0078, 0.0078, 0.0078],
         [0.0039, 0.0118, 0.0039,  ..., 0.0078, 0.0078, 0.0078],
         ...,
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.0078, 0.0157, 0.0078,  ..., 0.0078, 0.0078, 0.0078],
         [0.0078, 0.0157, 0.0078,  ..., 0.0078, 0.0078, 0.0078],
         [0.0039, 0.0118, 0.0039,  ..., 0.0078, 0.0078, 0.0078],
         ...,
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.0078, 0.0157, 0.0078,  ..., 0.0078, 0.0078, 0.0078],
         [0.0078, 0.0157, 0.0078,  ..., 0.0078, 0.0078, 0.0078],
         [0.0039, 0.0118, 0.0039,  ..., 0.0078, 0.0078, 

[(tensor([[[0.0000, 0.0000, 0.0000,  ..., 0.0588, 0.0667, 0.0549],
         [0.0000, 0.0000, 0.0000,  ..., 0.0706, 0.0745, 0.0588],
         [0.0000, 0.0000, 0.0000,  ..., 0.0784, 0.0824, 0.0706],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 1.0000, 0.9725, 0.5373],
         [0.0000, 0.0000, 0.0000,  ..., 0.9882, 0.9608, 0.5647],
         [0.0000, 0.0000, 0.0000,  ..., 0.5294, 0.5490, 0.2196]],

        [[0.0000, 0.0000, 0.0000,  ..., 0.0588, 0.0667, 0.0549],
         [0.0000, 0.0000, 0.0000,  ..., 0.0706, 0.0745, 0.0588],
         [0.0000, 0.0000, 0.0000,  ..., 0.0784, 0.0824, 0.0706],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 1.0000, 0.9725, 0.5373],
         [0.0000, 0.0000, 0.0000,  ..., 0.9882, 0.9608, 0.5647],
         [0.0000, 0.0000, 0.0000,  ..., 0.5294, 0.5490, 0.2196]],

        [[0.0000, 0.0000, 0.0000,  ..., 0.0588, 0.0667, 0.0549],
         [0.0000, 0.0000, 0.0000,  ..., 0.0706, 0.0745, 0.0588],
         [0.0000, 0.0000, 0.0000,  ..., 0.0784, 0.0824, 

[(tensor([[[0.0039, 0.0039, 0.0039,  ..., 0.0118, 0.0118, 0.0157],
         [0.0039, 0.0039, 0.0039,  ..., 0.0118, 0.0118, 0.0157],
         [0.0039, 0.0039, 0.0039,  ..., 0.0118, 0.0118, 0.0157],
         ...,
         [0.0039, 0.0039, 0.0039,  ..., 0.0392, 0.0392, 0.0392],
         [0.0039, 0.0039, 0.0039,  ..., 0.0392, 0.0392, 0.0392],
         [0.0039, 0.0039, 0.0039,  ..., 0.0392, 0.0392, 0.0392]],

        [[0.0039, 0.0039, 0.0039,  ..., 0.0118, 0.0118, 0.0157],
         [0.0039, 0.0039, 0.0039,  ..., 0.0118, 0.0118, 0.0157],
         [0.0039, 0.0039, 0.0039,  ..., 0.0118, 0.0118, 0.0157],
         ...,
         [0.0039, 0.0039, 0.0039,  ..., 0.0392, 0.0392, 0.0392],
         [0.0039, 0.0039, 0.0039,  ..., 0.0392, 0.0392, 0.0392],
         [0.0039, 0.0039, 0.0039,  ..., 0.0392, 0.0392, 0.0392]],

        [[0.0039, 0.0039, 0.0039,  ..., 0.0118, 0.0118, 0.0157],
         [0.0039, 0.0039, 0.0039,  ..., 0.0118, 0.0118, 0.0157],
         [0.0039, 0.0039, 0.0039,  ..., 0.0118, 0.0118, 

[(tensor([[[0.4392, 0.2157, 0.2235,  ..., 0.2706, 0.2627, 0.5922],
         [0.3098, 0.0784, 0.0863,  ..., 0.1412, 0.1412, 0.4863],
         [0.3333, 0.0980, 0.0980,  ..., 0.1333, 0.1412, 0.5020],
         ...,
         [0.6588, 0.5176, 0.5294,  ..., 0.0902, 0.0980, 0.4824],
         [0.6549, 0.5137, 0.5294,  ..., 0.0902, 0.0980, 0.4824],
         [0.6314, 0.5137, 0.5137,  ..., 0.0941, 0.0941, 0.4471]],

        [[0.4392, 0.2157, 0.2235,  ..., 0.2706, 0.2627, 0.5922],
         [0.3098, 0.0784, 0.0863,  ..., 0.1412, 0.1412, 0.4863],
         [0.3333, 0.0980, 0.0980,  ..., 0.1333, 0.1412, 0.5020],
         ...,
         [0.6588, 0.5176, 0.5294,  ..., 0.0902, 0.0980, 0.4824],
         [0.6549, 0.5137, 0.5294,  ..., 0.0902, 0.0980, 0.4824],
         [0.6314, 0.5137, 0.5137,  ..., 0.0941, 0.0941, 0.4471]],

        [[0.4392, 0.2157, 0.2235,  ..., 0.2706, 0.2627, 0.5922],
         [0.3098, 0.0784, 0.0863,  ..., 0.1412, 0.1412, 0.4863],
         [0.3333, 0.0980, 0.0980,  ..., 0.1333, 0.1412, 

[(tensor([[[0.8392, 0.8196, 0.7843,  ..., 0.0118, 0.0118, 0.0118],
         [0.8275, 0.8078, 0.7725,  ..., 0.0118, 0.0118, 0.0118],
         [0.8196, 0.8039, 0.7725,  ..., 0.0118, 0.0118, 0.0118],
         ...,
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.9216, 0.9020, 0.8745,  ..., 0.0196, 0.0196, 0.0196],
         [0.9098, 0.8902, 0.8627,  ..., 0.0196, 0.0196, 0.0196],
         [0.9020, 0.8863, 0.8627,  ..., 0.0196, 0.0196, 0.0196],
         ...,
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.8941, 0.8745, 0.8431,  ..., 0.0078, 0.0078, 0.0078],
         [0.8824, 0.8627, 0.8314,  ..., 0.0078, 0.0078, 0.0078],
         [0.8745, 0.8588, 0.8314,  ..., 0.0078, 0.0078, 

[(tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]]), {'boxes': tensor([[201., 240., 233., 279.]], dtype=torch.float64), 'label': tensor([1])}), (tensor([[[0.0588, 0.0588, 0.0588,  ..., 0.0941, 0.0980, 0.0980],
         [0.0588, 0.0588, 0.0588,  ..., 0.0941, 0.0941

[(tensor([[[0.4980, 0.5608, 0.5922,  ..., 0.4392, 0.4431, 0.4431],
         [0.4745, 0.5412, 0.5765,  ..., 0.4431, 0.4471, 0.4471],
         [0.4627, 0.5373, 0.5725,  ..., 0.4667, 0.4667, 0.4588],
         ...,
         [0.3059, 0.3137, 0.3216,  ..., 0.3961, 0.4000, 0.4000],
         [0.3098, 0.3176, 0.3255,  ..., 0.3922, 0.3961, 0.3961],
         [0.3176, 0.3216, 0.3294,  ..., 0.3882, 0.3922, 0.3922]],

        [[0.4941, 0.5569, 0.5882,  ..., 0.4471, 0.4510, 0.4471],
         [0.4706, 0.5373, 0.5725,  ..., 0.4510, 0.4549, 0.4510],
         [0.4588, 0.5333, 0.5686,  ..., 0.4745, 0.4745, 0.4627],
         ...,
         [0.3020, 0.3098, 0.3176,  ..., 0.3961, 0.4000, 0.4000],
         [0.3059, 0.3137, 0.3216,  ..., 0.3922, 0.3961, 0.3961],
         [0.3137, 0.3176, 0.3255,  ..., 0.3882, 0.3922, 0.3922]],

        [[0.5176, 0.5804, 0.6078,  ..., 0.4431, 0.4471, 0.4549],
         [0.4941, 0.5608, 0.5922,  ..., 0.4471, 0.4510, 0.4588],
         [0.4824, 0.5569, 0.5882,  ..., 0.4706, 0.4706, 

[(tensor([[[0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         [0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         [0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         ...,
         [0.0588, 0.0588, 0.0588,  ..., 0.0353, 0.0353, 0.0353],
         [0.0588, 0.0588, 0.0588,  ..., 0.0353, 0.0353, 0.0353],
         [0.0588, 0.0588, 0.0588,  ..., 0.0353, 0.0353, 0.0353]],

        [[0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         [0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         [0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         ...,
         [0.0588, 0.0588, 0.0588,  ..., 0.0353, 0.0353, 0.0353],
         [0.0588, 0.0588, 0.0588,  ..., 0.0353, 0.0353, 0.0353],
         [0.0588, 0.0588, 0.0588,  ..., 0.0353, 0.0353, 0.0353]],

        [[0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         [0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 0.0353],
         [0.0667, 0.0667, 0.0667,  ..., 0.0353, 0.0353, 

[(tensor([[[0.9412, 0.9490, 0.9490,  ..., 0.0000, 0.0000, 0.0000],
         [0.9490, 0.9529, 0.9490,  ..., 0.0000, 0.0000, 0.0000],
         [0.9529, 0.9569, 0.9451,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.9412, 0.9490, 0.9490,  ..., 0.0000, 0.0000, 0.0000],
         [0.9490, 0.9529, 0.9490,  ..., 0.0000, 0.0000, 0.0000],
         [0.9529, 0.9569, 0.9451,  ..., 0.0000, 0.0000, 0.0000],
         ...,
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],

        [[0.9412, 0.9490, 0.9490,  ..., 0.0000, 0.0000, 0.0000],
         [0.9490, 0.9529, 0.9490,  ..., 0.0000, 0.0000, 0.0000],
         [0.9529, 0.9569, 0.9451,  ..., 0.0000, 0.0000, 

[(tensor([[[0.0157, 0.0157, 0.0157,  ..., 0.3804, 0.3922, 0.4000],
         [0.0157, 0.0157, 0.0157,  ..., 0.3961, 0.3961, 0.3961],
         [0.0157, 0.0157, 0.0157,  ..., 0.4078, 0.4039, 0.3882],
         ...,
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.0157, 0.0157, 0.0157,  ..., 0.3804, 0.3922, 0.4000],
         [0.0157, 0.0157, 0.0157,  ..., 0.3961, 0.3961, 0.3961],
         [0.0157, 0.0157, 0.0157,  ..., 0.4078, 0.4039, 0.3882],
         ...,
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039],
         [0.0039, 0.0039, 0.0039,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.0157, 0.0157, 0.0157,  ..., 0.3804, 0.3922, 0.4000],
         [0.0157, 0.0157, 0.0157,  ..., 0.3961, 0.3961, 0.3961],
         [0.0157, 0.0157, 0.0157,  ..., 0.4078, 0.4039, 

[(tensor([[[0.9961, 0.9882, 1.0000,  ..., 0.9843, 0.9804, 0.9922],
         [0.9961, 0.9922, 1.0000,  ..., 1.0000, 1.0000, 0.9922],
         [0.9922, 0.9922, 1.0000,  ..., 0.9765, 1.0000, 0.9882],
         ...,
         [1.0000, 0.9961, 0.9961,  ..., 0.9686, 0.9961, 1.0000],
         [1.0000, 0.9961, 0.9922,  ..., 1.0000, 1.0000, 0.9922],
         [0.9922, 0.9882, 0.9882,  ..., 0.9725, 0.9922, 1.0000]],

        [[0.9961, 0.9882, 1.0000,  ..., 0.9843, 0.9804, 0.9922],
         [0.9961, 0.9922, 1.0000,  ..., 1.0000, 1.0000, 0.9922],
         [0.9922, 0.9922, 1.0000,  ..., 0.9765, 1.0000, 0.9882],
         ...,
         [1.0000, 0.9961, 0.9961,  ..., 0.9686, 0.9961, 1.0000],
         [1.0000, 0.9961, 0.9922,  ..., 1.0000, 1.0000, 0.9922],
         [0.9922, 0.9882, 0.9882,  ..., 0.9725, 0.9922, 1.0000]],

        [[0.9961, 0.9882, 1.0000,  ..., 0.9843, 0.9804, 0.9922],
         [0.9961, 0.9922, 1.0000,  ..., 1.0000, 1.0000, 0.9922],
         [0.9922, 0.9922, 1.0000,  ..., 0.9765, 1.0000, 

[(tensor([[[0.1176, 0.1020, 0.0863,  ..., 0.0392, 0.0157, 0.0157],
         [0.1098, 0.0980, 0.0824,  ..., 0.0471, 0.0078, 0.0078],
         [0.0980, 0.0902, 0.0784,  ..., 0.0510, 0.0000, 0.0000],
         ...,
         [0.2157, 0.1882, 0.1490,  ..., 0.0941, 0.1020, 0.1020],
         [0.2078, 0.1882, 0.1569,  ..., 0.0941, 0.0980, 0.0980],
         [0.2039, 0.1843, 0.1569,  ..., 0.0980, 0.1020, 0.1020]],

        [[0.1176, 0.1020, 0.0863,  ..., 0.0392, 0.0157, 0.0157],
         [0.1098, 0.0980, 0.0824,  ..., 0.0471, 0.0078, 0.0078],
         [0.0980, 0.0902, 0.0784,  ..., 0.0510, 0.0000, 0.0000],
         ...,
         [0.2157, 0.1882, 0.1490,  ..., 0.0941, 0.1020, 0.1020],
         [0.2078, 0.1882, 0.1569,  ..., 0.0941, 0.0980, 0.0980],
         [0.2039, 0.1843, 0.1569,  ..., 0.0980, 0.1020, 0.1020]],

        [[0.1176, 0.1020, 0.0863,  ..., 0.0392, 0.0157, 0.0157],
         [0.1098, 0.0980, 0.0824,  ..., 0.0471, 0.0078, 0.0078],
         [0.0980, 0.0902, 0.0784,  ..., 0.0510, 0.0000, 

[(tensor([[[0.9412, 0.9333, 0.9294,  ..., 0.0902, 0.1922, 0.2706],
         [0.9294, 0.9216, 0.9255,  ..., 0.0902, 0.1922, 0.2745],
         [0.9216, 0.9137, 0.9216,  ..., 0.0941, 0.2000, 0.2824],
         ...,
         [0.9020, 0.8902, 0.8784,  ..., 0.0039, 0.0039, 0.0039],
         [0.9333, 0.9137, 0.9098,  ..., 0.0039, 0.0039, 0.0039],
         [0.9412, 0.9216, 0.9176,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.9412, 0.9333, 0.9294,  ..., 0.0902, 0.1922, 0.2706],
         [0.9294, 0.9216, 0.9255,  ..., 0.0902, 0.1922, 0.2745],
         [0.9216, 0.9137, 0.9216,  ..., 0.0941, 0.2000, 0.2824],
         ...,
         [0.9020, 0.8902, 0.8784,  ..., 0.0039, 0.0039, 0.0039],
         [0.9333, 0.9137, 0.9098,  ..., 0.0039, 0.0039, 0.0039],
         [0.9412, 0.9216, 0.9176,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.9412, 0.9333, 0.9294,  ..., 0.0902, 0.1922, 0.2706],
         [0.9294, 0.9216, 0.9255,  ..., 0.0902, 0.1922, 0.2745],
         [0.9216, 0.9137, 0.9216,  ..., 0.0941, 0.2000, 

In [86]:
model.eval()
data = iter(val_dl).__next__()